# Generated by Django 3.0.2 on 2020-01-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200118_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Tecnologia'), ('CR', 'Curiosidades'), ('LIT', 'Literatura'), ('SCI', 'Ciências'), ('GR', 'Geral')], default='GR', max_length=3),
        ),
    ]
