# Generated by Django 3.0.2 on 2020-01-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted',
        ),
    ]
